### ISSUE TITLE
Exposed api key

### ISSUE THREAD

**Issue by ikuamike** [mayeedwin/devfest#1]
You have an exposed api key and other important config in this [index.html](https://github.com/mayeedwin/devfest/blob/master/app/index.html). It's easily viewable when you check the website source, It's a potential risk for your website.

**Comment by mayeedwin** [comment]
Thanks for the heads up. Working on that : )

**Comment by ikuamike** [comment]
You should avoid making such important configurations public, it's really a security risk.
